### PR TITLE
Create makefile with venv commands

### LINKED ISSUE #10: Automated venv process
## Description
It is time consuming and can be very easy to mess up building a virtual environment, especially with multiple python versions on your system. The steps for this should be automated in a makefile.

## Acceptance Criteria
- [ ] Create virtual environment with make command
- [ ] Update virtual environment with make command
- [ ] Rebuild virtual environment with make command

### PR DESCRIPTION
**Pull request by sarahmaas**
Resolves #10

## Description
Adds makefile with basic features for venv build, update, and rebuild as well as running the app.

## AC
- [x]  Create virtual environment with make command
- [x] Update virtual environment with make command
- [x] Rebuild virtual environment with make command

## Testing 
All commands were extensively tested in a linux environment.

### CODE REVIEW

**Comment by hschallh** [comment]
Students starting after F19 won't know what a makefile is. Should we add some instructions to the readme on how to run make rules?

**Comment by sarahmaas** [comment]
Fair point, what do you think of adding a docs folder, putting more detailed instructions there, and linking to it in the readme?

**Comment by hschallh** [comment]
Eh. Whatever's easier. Up to you!

**Review by hschallh — APPROVED** [review]
Looks good!

**Pull request merged**
